Test
KirillTarasenk0/laravel-learning pull request #1
Opened 2024-02-04 14:19 UTC by KirillTarasenk0

2024-02-12 13:41 UTC, KirillTarasenk0 commented
Я немножко неправильно сделал, надо было под каждое дз создавать новую ветку, а я этого не сделал во время выполнения третьего дз(сделал его в ветке, где второе дз), поэтому получилось что в одной ветке у меня два дз

2024-02-14 18:38 UTC, FilipovskyAlex requested changes

2024-02-14 18:38 UTC, FilipovskyAlex commented on routes/web.php
> +/*Route::get('/', function () {
лишние комменты удаляем

2024-02-14 18:38 UTC, FilipovskyAlex commented on routes/web.php
> +Route::get('/user/{id?}', function (?int $id = null) {
можно просто писать int $id = null, этот ? избыточен в данном случае, так как мы не передаем null, мы просто ничего не передаем и тогда сеттим null

2024-02-14 18:38 UTC, FilipovskyAlex commented on routes/web.php
> +Route::get('/api/users', function () {
тут была подсказка, что это api роут, следовательно мы их храним в api файле

2024-02-14 18:38 UTC, FilipovskyAlex commented on routes/web.php
> +    return redirect('/new-home');
данный роут у тебя не определен, куда ты редиректишь

2024-02-14 18:38 UTC, FilipovskyAlex commented on resources/views/form.blade.php
> +        @csrf
сможешь рассказать на занятии что такое csrf?

2024-02-14 19:01 UTC, FilipovskyAlex requested changes

2024-02-14 19:01 UTC, FilipovskyAlex commented
Отписал сразу по 2 дз

2024-02-16 13:39 UTC, KirillTarasenk0 commented on routes/web.php
> +    return redirect('/new-home');
я думал просто на любой рандомный роут редиректнуть можно, типо с самим методом поработать. сейчас роут определю

2024-02-16 13:40 UTC, KirillTarasenk0 commented on resources/views/form.blade.php
> +        @csrf
да

2024-02-16 14:31 UTC, KirillTarasenk0 commented on database/migrations/2024_02_07_124529_update_test_products.php
>       */
Предыдущее замечние исправил, не прочитав этот комментарий. На будущее запомню.

2024-02-16 14:42 UTC, KirillTarasenk0 commented on app/Models/TestProduct.php
> +    protected static function newFactory(): Factory
чтобы присвоить модель конкретной фабрике, если сам ларавель не свяжет модель с фабрикой. для перестраховки определил его

2024-02-19 06:28 UTC, FilipovskyAlex approved these changes

2024-02-19 06:28 UTC, merged