HW-41
KirillTarasenk0/laravel-learning pull request #3
Opened 2024-02-19 14:49 UTC by KirillTarasenk0

В UdpateCustomerProfileController немножко не понял, в чём проблема. Пытался обновить данные в базе через update метод, но вылазила ошибка(Column not found: 1054 Unknown column &#039;0&#039; in &#039;field list&#039; (Connection: mysql, SQL: update `customers` set `0` = contactFirstName, `1` = Kirill, `2` = contactLastName, `3` = Tarasenko, `4` = phone, `5` = 375447967653, `6` = postalCode, `7` = 123 where `customerNumber` = 119)), сделал через прямое присовение каждому полю нового значения, но почему не работает update сколько не пытался разобраться так и не понял(

2024-02-19 21:22 UTC, KirillTarasenk0 commented
Я исправил эту проблему. Она заключалась в том, что я неправильно метод update использовал)) там формат передачи значений ключ-значение, а я по невнимательности через запятую передал)

2024-03-03 11:03 UTC, FilipovskyAlex commented on app/Http/Controllers/UpdateCustomerProfileController.php
> +        $request->validated();
нам не нужно вызывать этот метод, если мы используем свой класс валидации, если у тебя не пройдет валидация, то Request твой автоматически выкинет 422

2024-03-03 11:05 UTC, FilipovskyAlex commented on app/Http/Requests/UpdateCustomerProfileRequest.php
> +    protected function failedValidation(Validator $validator)
и вот этот метод переопределять нет смысла, laravel выкинет это по ум.

2024-03-03 11:07 UTC, FilipovskyAlex commented on app/Rules/EmployeeNumber.php
> +        if ($value !== 5) {
а вот так делать нехорошо. У тебя здесь строгое задание id, в будущем таблица может поменяться, может быть к примеру сделан truncate и все id могут измениться. Если задание проверить по Токио, то это лучше делать как сказано в задаче, по названию города проверять. Причем само название города полезно выносить в константы, файл конфига или тому подобное, чтобы у тебя была одно место, где явно определяется данный параметр фильтрации

2024-03-03 11:14 UTC, FilipovskyAlex requested changes

2024-03-03 11:14 UTC, FilipovskyAlex commented on app/Http/Controllers/ProductController.php
> +    public function index(Request $request): JsonResponse
вот тут у тебя будет работать только в том случае, если мы передаем только 1 фильтр. А если сразу все 3?

Тут принцип тот же, что и в любых магазинах. Фильтрация множественная по принципу "1 фильтр И 2 фильтр И 3 фильтр"

2024-03-03 11:18 UTC, FilipovskyAlex commented
<img width="962" alt="image" src="https://github.com/KirillTarasenk0/laravel-learning/assets/43860174/408eb8c5-2820-4f73-9d6e-76b9578e7a0c">
вот эту не сделал

2024-03-16 19:35 UTC, FilipovskyAlex approved these changes

2024-03-22 23:54 UTC, merged