HW42 was made
KirillTarasenk0/laravel-learning pull request #4
Opened 2024-02-21 20:51 UTC by KirillTarasenk0

2024-03-09 09:17 UTC, FilipovskyAlex requested changes

2024-03-09 09:17 UTC, FilipovskyAlex commented on routes/api.php
> +Route::get('/payment', function () {
а чего где-то через group, где-то просто? можно же объеденить все в одну группу

2024-03-09 09:17 UTC, FilipovskyAlex commented on routes/web.php
> +})->middleware(\App\Http\Middleware\MaintenanceMode::class);
данный мидлвар должен быть глобальным, чтобы на какой бы роут мы не попали, если тех. работы, нам отдавался view tech. work

2024-03-09 09:17 UTC, FilipovskyAlex commented on app/Http/Middleware/CheckAdminToken.php
> +        if ($request->header('Authorization') === 'Admin') {
токен, это именно токен (уникальная последовательность символов, которая зашита в настройках приложения, чтобы никто не мог имитировать действия админа. В твоем случае я просто могу передать header admin, от обычного пользователя, а если есть токен, то, обычно он есть у узкого круга лиц (админы и пр.)

2024-03-12 00:42 UTC, KirillTarasenk0 commented on app/Http/Middleware/CheckAdminToken.php
> +        if ($request->header('Authorization') === 'Admin') {
Просто в условии было написано, что токен должен передаваться в headers, вот я и подумал)

2024-03-12 00:51 UTC, KirillTarasenk0 commented on routes/web.php
> +})->middleware(\App\Http\Middleware\MaintenanceMode::class);
Так он же у меня глобальный. Я его указал в свойстве $middleware в kernel файле. Сейчас проверяю, у меня при изменении роута и включении режима тех работ в конфиге идёт редирект на страницу с инфой, что проводятся технические работы. Может я что-то не так понял?

2024-03-12 22:57 UTC, KirillTarasenk0 commented on app/Http/Middleware/CheckAdminToken.php
> +        if ($request->header('Authorization') === 'Admin') {
Я исправил, но я почему-то когда просматриваю файлы в пулл реквесте не вижу изменений. При этом если в репозитории переключаюсь на эту ветку, то всё на месте.

2024-03-16 19:37 UTC, FilipovskyAlex commented on routes/web.php
> +})->middleware(\App\Http\Middleware\MaintenanceMode::class);
так если ты указал его там, то тут не нужно вызывать) он будет у тебя работать теперь на любой request

2024-03-23 23:51 UTC, merged