HW44 was made
KirillTarasenk0/laravel-learning pull request #6
Opened 2024-02-25 16:07 UTC by KirillTarasenk0

Всё тестировал постманом

2024-03-09 09:41 UTC, FilipovskyAlex requested changes

2024-03-09 09:41 UTC, FilipovskyAlex commented on app/Http/Controllers/RedisPostController.php
> +        dd($posts->pluck('title'));
давай без dd, я объяснял, что dd - это чисто пока ты делаешь задачу, проверить так скажем. А в реале возвращаем значение как положено

2024-03-09 09:41 UTC, FilipovskyAlex commented on app/Jobs/SendCustomerPaymentsReports.php
> +        private readonly string|null $timeFrom,
а чего так пишешь? string|null тебе так удобнее? можно же ?string

2024-03-09 09:41 UTC, FilipovskyAlex commented on app/Jobs/SendCustomerPaymentsReports.php
> +        if ($this->customerNumber) {
посмотри больше про eloquent, с ним такого рода код оформлять легче

Как пример:

```
Payment::when($customerNumber, function($query) use($customerNumber) {
  $query->whereHas('customer', function($query) use($customerNumber){
    $query->where('customers.customerNumber', $customerNumber)
  })
})
```

и по аналогии с from&to

2024-03-13 00:27 UTC, KirillTarasenk0 commented on app/Jobs/SendCustomerPaymentsReports.php
> +        private readonly string|null $timeFrom,
?string более элегантно и правильно, но так привык и более наглядно что ли получается

2024-03-16 19:41 UTC, FilipovskyAlex approved these changes

2024-03-23 23:56 UTC, merged