HW45 was made
KirillTarasenk0/laravel-learning pull request #7
Opened 2024-03-01 21:28 UTC by KirillTarasenk0

2024-03-10 12:54 UTC, FilipovskyAlex requested changes

2024-03-10 12:54 UTC, FilipovskyAlex commented on app/Observers/CustomerObserver.php
> +    /**
все лишнее удаляем, оно захломляет файл

2024-03-10 12:54 UTC, FilipovskyAlex commented on app/Http/Controllers/OrderStatusController.php
> +        $order = Order::find($orderNumber);
есть такая фукнция - findOrFail, посмотри что она делает

2024-03-10 12:54 UTC, FilipovskyAlex commented on app/Http/Controllers/CustomerController.php
> +                $order->orderDetails()->delete();
как раз-таки эти действия должны происходить в observer

2024-03-15 00:07 UTC, KirillTarasenk0 commented on app/Http/Controllers/CustomerController.php
> +                $order->orderDetails()->delete();
Вынес всё в обсёрвер, кроме orderdetails. Он напрямую с кастомером не связан(что должно быть по условию) + возникала ошибка целостности БД, если кастомера удаляю раньше orderdetails

2024-03-16 19:42 UTC, FilipovskyAlex approved these changes

2024-03-24 00:00 UTC, merged